apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: final-project
type: Opaque
stringData:
  POSTGRES_DB: "vaultedkubedb"
  POSTGRES_USER: "vaultedkube"
  POSTGRES_PASSWORD: "dW6RsV650P-GmBI90Sq#uw0L"
  DATABASE_URL: "postgresql://vaultedkube:dW6RsV650P-GmBI90Sq#uw0L@vaultedkube-postgres.cghcymykc28f.us-east-1.rds.amazonaws.com:5432/vaultedkubedb"
